### PR TITLE
NEP-1519: Enter to Apply

### PR DESCRIPTION
**Pull request by dn-readytech**
Updates all filter input components to apply filters when the `Enter` key
is pressed.

### CODE REVIEW

**Comment by dinusha-b14** [comment]
great attempt @dcnorman however do you think we might be able to define the function once and then pass it around to all inputs?

**Comment by dn-readytech** [comment]
@dinusha-b14 possibly, it does differ somewhat (`onBlur` vs `onSelect` prior to filter application) between input types.

**Comment by dinusha-b14** [comment]
@dcnorman maybe create two functions and pass them around to the different types

**Comment by dinusha-b14** [comment]
👍

**Pull request merged**
