### PR TITLE
[NEP-3751] Add DateTime input

### PR DESCRIPTION
**Pull request by louman**
https://jobready.atlassian.net/browse/NEP-3751

### CODE REVIEW

**Comment by andrba** [comment]
Can we use composition or subclass `DateInput`? They look very similar

**Comment by louman** [comment]
I tried, spent almost the whole day trying to make it work, couldn't...

**Comment by louman** [comment]
up @andrba

**Review by ghost — APPROVED** [review]
+1 It works! :)

**Pull request merged**
