### PR TITLE
[NEP-16784] Create count in date range filter type

### PR DESCRIPTION
**Pull request by JordanMooreNZ**
https://jobready.atlassian.net/browse/NEP-16784

Create new type of filter which will submit `operator, from, to, value and count` e.g:
```
[
{"uid":"published_on_count_in_date_range","type":"count_in_date_range","field":"published_on",
"value":{"operator":">","from":null,"to":null,"value":"Last+Week","count":"10"}}
]
```
or:
```
[
{"uid":"published_on_count_in_date_range","type":"count_in_date_range","field":"published_on",
"value":{"operator":">","from":"30/10/2023","to":"14/11/2023","value":null,"count":"10"}}
]
```
Made changes to the existing RelativeDateInput so that it'd be compatible to be utilised in this new component

Doesn't return any result in the dummy app since it's too complicated and preferably I'll just have to deal with that logic on Neptune side. This ticket was to create the FE input component that successfully submits the desired params.

image

image

### CODE REVIEW

**Review by yxawpKL — APPROVED** [review]
good stuff

**Comment by hanpeic** [comment]
looks good, just one question.
if user inputs number and select dates, click apply, and refreshes the page, are they still there

**Comment by JordanMooreNZ** [comment]
> looks good, just one question. if user inputs number and select dates, click apply, and refreshes the page, are they still there

@hanpeic can confirm they are still there on refresh, operating just like the other existing filters 👍

**Review by hanpeic — APPROVED** [review]
+1

**Comment by JordanMooreNZ** [comment]
Latest commit changes:

Update input order following feedback from Product
image

Update equals operator from `=` to `==`
```
[{"uid":"published_on_count_in_date_range","type":"count_in_date_range","field":"published_on",
"value":{"operator":"==","from":null,"to":null,"value":"Older+than+7+days","count":"10"}}]
```

**Review by yxawpKL — APPROVED** [review]
+1

**Pull request merged**
